### ISSUE TITLE
project moved

### ISSUE THREAD

**Issue by 4kplayeee** [baontq23/Logos-API-Authentication#3]
the new api-server in english and improved api-server website: https://ios-api-server.xyz/

Twitter : @ios_APIServer

**Comment by 4kplayeee** [comment]
bro your not hosting it anymore

**Comment by baontq23** [comment]
I'm still maintaining it and APIServer mobile app called "myDash". API V5 coming soon with new Dashboard UI, seller system,...

**Comment by 4kplayeee** [comment]
Interesting
